version: "3"

services:
    postgres:
        image: postgres
        container_name: "pgdb"
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=db_user
            - POSTGRES_PASSWORD=pwd123
        volumes:
            - /home/hwndrer/rebrain/db/data:/var/lib/postgresql/data
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080